CREATE WAREHOUSE IF NOT EXISTS WH_SALES_ANALYTICS_2026
  WITH WAREHOUSE_SIZE = 'XSMALL'
  AUTO_SUSPEND = 60
  AUTO_RESUME = TRUE;

CREATE DATABASE IF NOT EXISTS DB_SALES_2026;

USE DATABASE DB_SALES_2026;
USE SCHEMA PUBLIC;

CREATE STAGE IF NOT EXISTS STG_RAW_SALES_2026;
