USE WAREHOUSE WH_SALES_ANALYTICS_2026;
USE DATABASE DB_SALES_2026;
USE SCHEMA PUBLIC;


DROP TABLE IF EXISTS RAW_SUPERSTORE;


CREATE OR REPLACE FILE FORMAT FF_CSV_GENERIC
    TYPE = 'CSV'
    FIELD_DELIMITER = ','
    FIELD_OPTIONALLY_ENCLOSED_BY = '"'
    NULL_IF = ('NULL', 'null', '')
    PARSE_HEADER = TRUE;


CREATE OR REPLACE TABLE RAW_SUPERSTORE USING TEMPLATE (
    SELECT ARRAY_AGG(OBJECT_CONSTRUCT(*))
    FROM TABLE(
        INFER_SCHEMA(
            LOCATION => '@STG_RAW_SALES_2026/01_superstore.csv',
            FILE_FORMAT => 'FF_CSV_GENERIC'
        )
    )
);


COPY INTO RAW_SUPERSTORE
FROM @STG_RAW_SALES_2026/01_superstore.csv
FILE_FORMAT = (FORMAT_NAME = 'FF_CSV_GENERIC')
MATCH_BY_COLUMN_NAME = CASE_INSENSITIVE;


SELECT * 
FROM RAW_SUPERSTORE 
LIMIT 10;


SELECT COUNT(*) AS TOTAL_REGISTROS 
FROM RAW_SUPERSTORE;
