USE WAREHOUSE WH_SALES_ANALYTICS_2026;
USE DATABASE DB_SALES_2026;
USE SCHEMA PUBLIC;

DESC TABLE RAW_SUPERSTORE;

SELECT *
FROM RAW_SUPERSTORE
LIMIT 10;

SELECT 
    HASH(* EXCLUDE "Row ID") AS HUELLA_NEGOCIO,
    COUNT(*) AS REPETICIONES
FROM RAW_SUPERSTORE
GROUP BY HUELLA_NEGOCIO
HAVING COUNT(*) > 1;


DELETE FROM RAW_SUPERSTORE
WHERE "Row ID" IN (1700, 392);
