USE WAREHOUSE WH_SALES_ANALYTICS_2026;
USE DATABASE DB_SALES_2026;
CREATE SCHEMA IF NOT EXISTS GOLD;


-- DIM_CUSTOMER
CREATE OR REPLACE TABLE DB_SALES_2026.GOLD.DIM_CUSTOMER AS
SELECT DISTINCT
    customer_id,
    customer_name,
    segment
FROM DB_SALES_2026.SILVER.SUPERSTORE;


-- DIM_PRODUCT
CREATE OR REPLACE TABLE DB_SALES_2026.GOLD.DIM_PRODUCT AS
SELECT DISTINCT
    product_id,
    category,
    sub_category,
    product_name
FROM DB_SALES_2026.SILVER.SUPERSTORE;
